### ISSUE TITLE
Some problems about data-preprocessing module

### ISSUE THREAD

**Issue by Peggy1027** [enoche/MMRec#3]
Your work is impressive and helpful for beginners like me to understand the multi-modal recommendation system. But I encountered two problems when running your data-preprocessing module: 1. Your data-preprocessing module seems unable to handle the "complete review data"; I would like to know if you can release these codes; 2. During the remapping process in the "2reindex-feat.ipynb", I found that there would be a mismatch, so the map_dict would be empty. Except for processing the string "true" and "false" in the parse function and modifying the file path, I made no changes. Is there anything wrong?

**Comment by enoche** [comment]
Hi, Peggy1027, thanks for running our code and giving the above feedback.
1. Sorry we didn't have the code for preprocessing "complete review data" in http://jmcauley.ucsd.edu/data/amazon/links.html. Because we only use the "Per-category files" and "Files-"Small" subsets for experimentation" rating files. 
2. May we have more detailed information about the content of your 'i_id_mapping' file? Also, we encourage you to use the debugging of IDE/CMD to check why map_dict would be empty. 
Happy that we can help your research on this topic.

**Comment by fattypiggy** [comment]
@enoche so the rating files link is http://snap.stanford.edu/data/amazon/productGraph/item_dedup.csv ? 3.2gb in total

**Comment by fattypiggy** [comment]
oh, I finally know what you mean, thanks for your nice project.
